Repository umairkhalid/movie-planner, pull requests merged in 2022-04, with the labels that each got.

#68 Updated callOMDB() - clear metadata stack
  assets/js/getMovieInfo.js
Labels: enhancement

#73 Added other contributors' names to License
  LICENSE
Labels: documentation

#70 Updated showTrailer.js: added clearTrailer()
  assets/js/modalPop.js
Labels: enhancement

#77 Changed http to https where possible
  assets/js/getMovieInfo.js
  index.html
Labels: bug

#85 Ken delete console log
  assets/js/getMovieInfo.js
  assets/js/modalPop.js
  assets/js/showTrailer.js
Labels: documentation

#87 CSS Comments for All Selectors
  assets/css/footer.css
  assets/css/header.css
  assets/css/style.css
Labels: documentation

#92 Update favicon, update favicon link, remove DS Store
  .gitignore
  assets/.DS_Store
  assets/mooveefavi.png
  index.html
Labels: enhancement

#97 Removed commented code
  assets/js/getMovieInfo.js
  assets/js/modalPop.js
  assets/js/showTrailer.js
Labels: documentation

#101 Fixed bug of metadata not aligning with title
  assets/js/getMovieInfo.js
  assets/js/images/noposter.png
Labels: bug

#113 moved noposter.png to Assets/images. Updated getMovieInfo
  assets/images/noposter.png
  assets/js/getMovieInfo.js
Labels: documentation

#112 111 readme should have contact info for all contributors
  README.md
Labels: documentation
